import { DM_Sans, Roboto_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const sans = DM_Sans({
  weight: ["400", "700"],
  variable: "--font-sans",
  subsets: ["latin"],
});

const mono = Roboto_Mono({
  weight: ["400", "700"],
  variable: "--font-mono",
  subsets: ["latin"],
});

const title = localFont({
  src: [
    {
      path: "./fonts/jp-pixel.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-title",
});

export const metadata = {
  title: "わからない",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${sans.variable} ${mono.variable} ${title.variable} font-sans bg-gray1`}
      >
        {children}
      </body>
    </html>
  );
}
