import React from "react";
import { DM_Sans, Roboto_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const sans = DM_Sans({
  weight: ["400", "700"],
  variable: "--font-sans",
  subsets: ["latin"],
});

const mono = Roboto_Mono({
  weight: ["400", "700"],
  variable: "--font-mono",
  subsets: ["latin"],
});

const title = localFont({
  src: [
    {
      path: "./fonts/jp-pixel.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-title",
});

export const metadata = {
  title: "wakaranai!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${sans.variable} ${mono.variable} ${title.variable} font-sans bg-gray-1 text-gray-12`}
      >
        <Background />
        {children}
      </body>
    </html>
  );
}

function Background() {
  const id = React.useId();
  return (
    <svg className="fixed inset-0" width="100%" height="100%">
      <defs>
        <pattern
          id={id}
          width="25"
          height="25"
          viewBox="0 0 10 10"
          patternUnits="userSpaceOnUse"
        >
          <circle cx="5" cy="5" r="1" className="fill-gray-3" />
        </pattern>
      </defs>
      <rect width="100%" height="100%" fill={`url(#${id})`} />
    </svg>
  );
}
